site_name: Documentación Proyecto Angular & WordPress | Practicas 2021-2 UNAB
theme: readthedocs
nav: 
    - 'CONTENIDO:':
      - Documentación: 'index.md'
    - 'Manual de usuario':
      - 'Sistema de autenticación': 'authenticated.md'
    - Acerca de: 'about.md'
