site_name: Documentación Proyecto Angular & WordPress | Practicas 2021-2 UNAB
theme: readthedocs
nav: 
    - 'CONTENIDO:':
      - Documentación: 'index.md'
      - Frontend: 'frontend.md'
      - Backend: 'backend.md'
